export const usersData = [
  { id: 1, name: 'Alice' },
  { id: 2, name: 'Bob' },
  { id: 3, name: 'Charlie' },
  { id: 4, name: 'David' },
  { id: 5, name: 'Eve' },
  { id: 6, name: 'Frank' },
  { id: 7, name: 'Grace' },
  { id: 8, name: 'Hank' },
  { id: 9, name: 'Ivy' },
  { id: 10, name: 'Jack' },
  { id: 11, name: 'Kathy' },
  { id: 12, name: 'Liam' },
  { id: 13, name: 'Mona' },
  { id: 14, name: 'Nina' },
  { id: 15, name: 'Oscar' },
  { id: 16, name: 'Paul' },
  { id: 17, name: 'Quincy' },
  { id: 18, name: 'Rachel' },
  { id: 19, name: 'Sam' },
  { id: 20, name: 'Tina' },
];
